[package]
name = "blinky"
version = "0.1.0"
authors = ["Nurahmadie <nurahmadie@gmail.com>"]

[dependencies]
stm32f401x = { git = "https://github.com/fudanchii/stm32f401x" }

[profile.release]
codegen-units = 1
lto = true
